plugins {
    id 'com.android.application'
    id 'com.google.dagger.hilt.android'
}

android {
    namespace "org.udg.pds.todoandroid"
    compileSdk 35

    defaultConfig {
        applicationId "org.udg.pds.todoandroid"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.7.1"
    implementation "com.google.android.material:material:1.13.0"
    implementation "androidx.constraintlayout:constraintlayout:2.2.1"

    // Lifecycle
    implementation "androidx.lifecycle:lifecycle-viewmodel:2.10.0"
    implementation "androidx.lifecycle:lifecycle-livedata:2.10.0"

    // RecyclerView
    implementation "androidx.recyclerview:recyclerview:1.4.0"

    // Room
    implementation "androidx.room:room-runtime:2.8.4"
    implementation 'androidx.navigation:navigation-fragment:2.9.7'
    implementation 'androidx.navigation:navigation-ui:2.9.7'
    annotationProcessor "androidx.room:room-compiler:2.8.4"

    // Retrofit + Gson + OkHttp
    implementation "com.squareup.retrofit2:retrofit:3.0.0"
    implementation "com.squareup.retrofit2:converter-gson:3.0.0"
    implementation 'com.squareup.okhttp3:logging-interceptor:5.3.2'
    implementation 'com.squareup.okhttp3:okhttp-urlconnection:5.3.2'

    // Hilt
    implementation "com.google.dagger:hilt-android:2.57.2"
    annotationProcessor "com.google.dagger:hilt-compiler:2.57.2"

    // Navigation Component
    implementation "androidx.navigation:navigation-fragment:2.9.6"
    implementation "androidx.navigation:navigation-ui:2.9.6"
}
